apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: searchlight-operator
  name: searchlight-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchlight-operator
  template:
    metadata:
      labels:
        app: searchlight-operator
    spec:
      containers:
      - args:
        - run
        - --icinga-secret-name=searchlight-icinga
        - --icinga-secret-namespace=kube-system
        - --v=3
        image: appscode/searchlight:1.5.9
        name: operator
