apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: appscode-searchlight
  name: appscode-searchlight
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: appscode-searchlight
  template:
    metadata:
      labels:
        run: appscode-searchlight
    spec:
      containers:
      - args:
        - --icinga-secret=k8s-icinga.default
        image: appscode/searchlight:docs
        imagePullPolicy: Always
        name: appscode-searchlight
