metadata:
  name: podalerts.monitoring.appscode.com
  labels:
    app: searchlight
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
spec:
  group: monitoring.appscode.com
  names:
    kind: PodAlert
    plural: podalerts
    shortNames: ["poa"]
  scope: Namespaced
  version: v1alpha1
---
metadata:
  name: nodealerts.monitoring.appscode.com
  labels:
    app: searchlight
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
spec:
  group: monitoring.appscode.com
  names:
    kind: NodeAlert
    plural: nodealerts
    shortNames: ["noa"]
  scope: Namespaced
  version: v1alpha1
---
metadata:
  name: clusteralerts.monitoring.appscode.com
  labels:
    app: searchlight
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
spec:
  group: monitoring.appscode.com
  names:
    kind: ClusterAlert
    plural: clusteralerts
    shortNames: ["ca"]
  scope: Namespaced
  version: v1alpha1
