apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: searchlight
  name: clusteralerts.monitoring.appscode.com
spec:
  group: monitoring.appscode.com
  names:
    kind: ClusterAlert
    listKind: ClusterAlertList
    plural: clusteralerts
    shortNames:
    - ca
    singular: clusteralert
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: searchlight
  name: incidents.monitoring.appscode.com
spec:
  group: monitoring.appscode.com
  names:
    kind: Incident
    listKind: IncidentList
    plural: incidents
    singular: incident
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: searchlight
  name: nodealerts.monitoring.appscode.com
spec:
  group: monitoring.appscode.com
  names:
    kind: NodeAlert
    listKind: NodeAlertList
    plural: nodealerts
    shortNames:
    - noa
    singular: nodealert
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: searchlight
  name: podalerts.monitoring.appscode.com
spec:
  group: monitoring.appscode.com
  names:
    kind: PodAlert
    listKind: PodAlertList
    plural: podalerts
    shortNames:
    - poa
    singular: podalert
  scope: Namespaced
  version: v1alpha1
