apiVersion: monitoring.appscode.com/v1alpha1
kind: ClusterAlert
metadata:
  name: json-path-demo-0
  namespace: demo
spec:
  check: json_path
  vars:
    url: https://api.appscode.com/health/json
    critical: '.metadata.env!="prod"'
  checkInterval: 30s
  alertInterval: 2m
  notifierSecretName: notifier-config
  receivers:
  - notifier: Mailgun
    state: CRITICAL
    to: ["ops@example.com"]
