apiVersion: monitoring.appscode.com/v1alpha1
kind: ClusterAlert
metadata:
  name: json-path-demo-1
  namespace: demo
spec:
  check: json-path
  vars:
    url: "http://validate.jsontest.com/?json=[ok,warning,critical]"
    critical: '{.size} != 3'
  checkInterval: 30s
  alertInterval: 2m
  notifierSecretName: notifier-config
  receivers:
  - notifier: Mailgun
    state: Critical
    to: ["ops@example.com"]
