apiVersion: v1
kind: Service
metadata:
  name: local-server
  namespace: demo
spec:
  ports:
  - name: api
    port: 443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: local-server
  namespace: demo
subsets:
- addresses:
  # list all external ips for this service
  - ip: 10.0.2.2
  ports:
  - name: api
    port: 8443
    protocol: TCP
---
# register as aggregated server
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.admission.monitoring.appscode.com
  labels:
    app: searchlight
spec:
  insecureSkipTLSVerify: true
  group: admission.monitoring.appscode.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: local-server
    namespace: demo
  version: v1alpha1
---
# register as aggregated server
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.incidents.monitoring.appscode.com
  labels:
    app: searchlight
spec:
  insecureSkipTLSVerify: true
  group: incidents.monitoring.appscode.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: local-server
    namespace: demo
  version: v1alpha1
