# register to intercept searchlight CRD creates / updates
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.monitoring.appscode.com
  labels:
    app: searchlight
webhooks:
- name: admission.monitoring.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.monitoring.appscode.com/v1alpha1/admissionreviews
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - monitoring.appscode.com
    apiVersions:
    - "*"
    resources:
    - "*"
  failurePolicy: Fail
