apiVersion: v1
kind: Secret
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
type: monitoring.appscode.com/icinga
data:
  HIPCHAT_AUTH_TOKEN: $HIPCHAT_AUTH_TOKEN
  HIPCHAT_TO: $HIPCHAT_TO
  MAILGUN_DOMAIN: $MAILGUN_DOMAIN
  MAILGUN_API_KEY: $MAILGUN_API_KEY
  MAILGUN_PUBLIC_API_KEY: $MAILGUN_PUBLIC_API_KEY
  MAILGUN_FROM: $MAILGUN_FROM
  MAILGUN_TO: $MAILGUN_TO
  SMTP_HOST: $SMTP_HOST
  SMTP_PORT: $SMTP_PORT
  SMTP_INSECURE_SKIP_VERIFY: $SMTP_INSECURE_SKIP_VERIFY
  SMTP_USERNAME: $SMTP_USERNAME
  SMTP_PASSWORD: $SMTP_PASSWORD
  SMTP_FROM: $SMTP_FROM
  SMTP_TO: $SMTP_TO
  TWILIO_ACCOUNT_SID: $TWILIO_ACCOUNT_SID
  TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN
  TWILIO_FROM: $TWILIO_FROM
  TWILIO_TO: $TWILIO_TO
  SLACK_AUTH_TOKEN: $SLACK_AUTH_TOKEN
  SLACK_CHANNEL: $SLACK_CHANNEL
  PLIVO_AUTH_ID: $PLIVO_AUTH_ID
  PLIVO_AUTH_TOKEN: $PLIVO_AUTH_TOKEN
  PLIVO_FROM: $PLIVO_FROM
  PLIVO_TO: $PLIVO_TO
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: searchlight
    spec:
      containers:
      - name: operator
        image: appscode/searchlight:canary
        args:
        - run
        - --notifier-secret-name=searchlight-operator
        - --v=3
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP     
      - image: appscode/icinga:3.0.0-k8s
        name: icinga
        ports:
        - containerPort: 5665
          name: api
          protocol: TCP
        - containerPort: 60006
          name: web
          protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: 5665
            path: /v1/status
            httpHeaders:
              - name: Authorization
                value: "Basic c3RhdHVzdXNlcjpzdGF0dXNwYXNz"
          initialDelaySeconds: 120
          periodSeconds: 30
        volumeMounts:
          - name: data-volume
            mountPath: /var/pv
          - name: script-volume
            mountPath: /var/db-script
          - name: icingaconfig
            mountPath: /srv/searchlight/secrets
      - image: appscode/postgres:9.5-v3-db
        name: ido
        args:
          - basic
          - './setup-db.sh'
        ports:
          - containerPort: 5432
            name: ido
            protocol: TCP
        volumeMounts:
          - name: data-volume
            mountPath: /var/pv
          - name: script-volume
            mountPath: /var/db-script
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: script-volume
          emptyDir: {}
        - name: icingaconfig
          secret:
            secretName: searchlight-operator
---
kind: Service
apiVersion: v1
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: api
    port: 5665
    targetPort: api
  - name: http
    port: 56790
    targetPort: web
  selector:
    app: searchlight
