apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: searchlight-operator
  namespace: default
  labels:
    app: searchlight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: searchlight
    spec:
      containers:
      - name: operator
        image: appscode/searchlight:canary
        imagePullPolicy: Always
        args:
        - run
        - --v=3
        - --config-dir=/srv
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /srv
          name: data
      - name: icinga
        image: appscode/icinga:canary
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5665
          name: api
          protocol: TCP
        - containerPort: 60006
          name: web
          protocol: TCP
        volumeMounts:
        - mountPath: /srv
          name: data
      - name: ido
        image: postgres:9.6-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: ido
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      volumes:
      - emptyDir: {}
        name: data
