apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: searchlight-operator
  namespace: default
  labels:
    app: searchlight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: searchlight
    spec:
      containers:
      - name: operator
        image: appscode/searchlight:canary
        imagePullPolicy: Always
        args:
        - run
        - --v=3
        - --config-dir=/srv
        ports:
        - name: http
          containerPort: 56790
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /srv
      - name: icinga
        image: appscode/icinga:canary
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 5665
          protocol: TCP
        - name: web
          containerPort: 60006
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /srv
      - name: ido
        image: postgres:9.6-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - name: ido
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        emptyDir: {}
