---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: component-status
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      v: vars.verbosity
    vars:
      Item:
        componentName:
          type: string
        selector:
          type: string
  command: hyperalert check_component_status
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: json-path
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
      Item:
        critical:
          type: string
        secretName:
          type: string
        url:
          type: string
        warning:
          type: string
      required:
      - url
  command: hyperalert check_json_path
  state:
  - OK
  - Warning
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: node-exists
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      v: vars.verbosity
    vars:
      Item:
        count:
          type: integer
        nodeName:
          type: string
        selector:
          type: string
  command: hyperalert check_node_exists
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: pod-exists
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
      Item:
        count:
          type: integer
        podName:
          type: string
        selector:
          type: string
  command: hyperalert check_pod_exists
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: event
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
      Item:
        clockSkew:
          type: duration
        involvedObjectKind:
          type: string
        involvedObjectName:
          type: string
        involvedObjectNamespace:
          type: string
        involvedObjectUID:
          type: string
  command: hyperalert check_event
  state:
  - OK
  - Warning
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: ca-cert
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      v: vars.verbosity
    vars:
      Item:
        critical:
          type: duration
        warning:
          type: duration
  command: hyperalert check_ca_cert
  state:
  - OK
  - Warning
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: cert
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
      Item:
        critical:
          type: duration
        secretKey:
          type: string
        secretName:
          type: string
        selector:
          type: string
        warning:
          type: duration
  command: hyperalert check_cert
  state:
  - OK
  - Warning
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: node-status
spec:
  alertKinds:
  - NodeAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
  command: hyperalert check_node_status
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: node-volume
spec:
  alertKinds:
  - NodeAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
      Item:
        critical:
          type: number
        mountPoint:
          type: string
        secretName:
          type: string
        warning:
          type: number
      required:
      - mountPoint
  command: hyperalert check_volume
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: pod-status
spec:
  alertKinds:
  - PodAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
  command: hyperalert check_pod_status
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: pod-volume
spec:
  alertKinds:
  - PodAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
      Item:
        critical:
          type: number
        secretName:
          type: string
        volumeName:
          type: string
        warning:
          type: number
      required:
      - volumeName
  command: hyperalert check_volume
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: pod-exec
spec:
  alertKinds:
  - PodAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
      Item:
        argv:
          type: string
        cmd:
          type: string
        container:
          type: string
      required:
      - argv
  command: hyperalert check_pod_exec
  state:
  - OK
  - Critical
  - Unknown
