apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: searchlight-operator
  labels:
    app: searchlight
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - monitoring.appscode.com
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - secrets
  - componentStatuses
  - persistentVolumes
  - persistentVolumeClaims
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: searchlight-operator
  labels:
    app: searchlight
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: searchlight-operator
subjects:
- kind: ServiceAccount
  name: $SEARCHLIGHT_SERVICE_ACCOUNT
  namespace: $SEARCHLIGHT_NAMESPACE
