kind: Service
apiVersion: v1
metadata:
  name: searchlight
  namespace: kube-system
  labels:
    app: searchlight
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: api
    port: 5665
    targetPort: api
  - name: http
    port: 56790
    targetPort: web
  selector:
    app: searchlight
