apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: searchlight-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs: ["get", "create"]
- apiGroups:
  - monitoring.appscode.com
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - secrets
  - componentStatuses
  - persistentVolumes
  - persistentVolumeClaims
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - pods
  - nodes
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: searchlight-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: searchlight-operator
subjects:
- kind: ServiceAccount
  name: searchlight-operator
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: searchlight-operator
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
data:
  ICINGA_WEB_UI_PASSWORD: changeit
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: searchlight
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: operator
        image: appscode/searchlight:canary
        imagePullPolicy: Always
        args:
        - run
        - --v=3
        - --config-dir=/srv
        - --notifier-secret-name=searchlight-operator
        ports:
        - name: http
          containerPort: 56790
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /srv
      - name: icinga
        image: appscode/icinga:canary
        imagePullPolicy: Always
        ports:
        - name: api
          containerPort: 5665
          protocol: TCP
        - name: web
          containerPort: 60006
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /srv
      - name: ido
        image: postgres:9.6-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - name: ido
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        emptyDir: {}
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
---
kind: Service
apiVersion: v1
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: api
    port: 5665
    targetPort: api
  - name: http
    port: 56790
    targetPort: web
  selector:
    app: searchlight
