apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: searchlight-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - monitoring.appscode.com
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - secrets
  - componentStatuses
  - persistentVolumes
  - persistentVolumeClaims
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: searchlight-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: searchlight-operator
subjects:
- kind: ServiceAccount
  name: searchlight-operator
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: searchlight-operator
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
data:
  ICINGA_WEB_UI_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: searchlight
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: searchlight-operator
      containers:
      - name: operator
        image: appscode/searchlight:4.0.0-rc.0
        imagePullPolicy: IfNotPresent
        args:
        - run
        - --v=3
        - --config-dir=/srv
        - --config-secret-name=searchlight-operator
        - --api.address=:8080
        - --web.address=:56790
        ports:
        - name: api
          containerPort: 8080
          protocol: TCP
        - name: web
          containerPort: 56790
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /srv
      - name: icinga
        image: appscode/icinga:4.0.0-rc.0-k8s
        imagePullPolicy: IfNotPresent
        ports:
        - name: icinga
          containerPort: 5665
          protocol: TCP
        - name: ui
          containerPort: 60006
          protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: 5665
            path: /v1/status
            httpHeaders:
              - name: Authorization
                value: "Basic c3RhdHVzdXNlcjpzdGF0dXNwYXNz"
          initialDelaySeconds: 120
          periodSeconds: 30
        volumeMounts:
        - name: data
          mountPath: /srv
      - name: ido
        image: appscode/postgres:9.5-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - name: ido
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        emptyDir: {}
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
---
kind: Service
apiVersion: v1
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
spec:
  ports:
  - name: ui
    port: 80
    targetPort: ui
  - name: icinga
    port: 5665
    targetPort: icinga
  - name: api
    port: 8080
    targetPort: api
  - name: web
    port: 56790
    targetPort: web
  selector:
    app: searchlight
