metadata:
  name: pod-alert.monitoring.appscode.com
  labels:
    app: searchlight  
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "Searchlight by AppsCode - Alerts for Kubernetes"
versions:
  - name: v1alpha1
---
metadata:
  name: node-alert.monitoring.appscode.com
  labels:
    app: searchlight
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "Searchlight by AppsCode - Node Alerts for Kubernetes"
versions:
  - name: v1alpha1
---
metadata:
  name: cluster-alert.monitoring.appscode.com
  labels:
    app: searchlight
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "Searchlight by AppsCode - Cluster Alerts for Kubernetes"
versions:
  - name: v1alpha1
