{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "searchlight.fullname" . }}
  labels:
    {{- include "searchlight.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs: ["get", "patch"]
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs: ["delete", "list", "watch", "patch"]
- apiGroups:
  - monitoring.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - storage.k8s.io
  resources:
  - "*"
  verbs: ["get"]
- apiGroups:
  - ""
  resources:
  - secrets
  - componentstatuses
  - persistentvolumes
  - persistentvolumeclaims
  verbs: ["get", "list"]
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs: ["get", "list", "patch", "watch"]
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs: ["create"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create", "list"]
- apiGroups:
  - ""
  resources:
  - services
  verbs: ["get"]
{{ end }}
