apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    app: {{ template "fullname" . }}-operator
  name: {{ template "fullname" . }}-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-operator
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-operator
    spec:
      containers:
      - args:
        - run
        - --icinga-secret-name={{ template "fullname" . }}-icinga
        - --icinga-secret-namespace={{.Release.Namespace}}
        - --v=3
        image: {{.Values.searchlight.image}}:{{.Values.searchlight.imageTag}}
        name: operator
