apiVersion: v1
kind: Service
metadata:
  name: {{ template "searchlight.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "searchlight.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: ui
    port: 80
    targetPort: ui
  - name: icinga
    port: 5665
    targetPort: icinga
  - name: api
    port: 8080
    targetPort: api
  selector:
    app: "{{ template "searchlight.name" . }}"
    release: "{{ .Release.Name }}"
