apiVersion: v1
kind: Service
metadata:
  name: {{ template "searchlight.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "searchlight.labels" . | nindent 4 }}
spec:
  ports:
  - name: ui
    port: 80
    targetPort: 60006
  - name: api
    port: 443
    targetPort: 8443
  - name: icinga
    port: 5665
    targetPort: 5665
  selector:
    app: "{{ template "searchlight.name" . }}"
    release: "{{ .Release.Name }}"
