{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:searchlight:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - monitoring.appscode.com
  resources:
  - clusteralerts
  - nodealerts
  - podalerts
  - incidents
  verbs: ["*"]
- apiGroups:
  - incidents.monitoring.appscode.com
  resources:
  - acknowledgements
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:searchlight:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - monitoring.appscode.com
  resources:
  - clusteralerts
  - nodealerts
  - podalerts
  verbs: ["*"]
- apiGroups:
  - monitoring.appscode.com
  resources:
  - incidents
  verbs: ["delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups:
  - incidents.monitoring.appscode.com
  resources:
  - acknowledgements
  verbs: ["create", "delete"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appscode:searchlight:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - monitoring.appscode.com
  resources:
  - clusteralerts
  - nodealerts
  - podalerts
  - incidents
  verbs: ["get", "list", "watch"]
{{ end }}
