apiVersion: monitoring.appscode.com/v1alpha1
kind: ClusterAlert
metadata:
  name: component-status-demo-1
  namespace: demo
spec:
  check: component_status
  vars:
    component: etcd-0
  checkInterval: 30s
  alertInterval: 2m
  notifierSecretName: any-notifier
  receivers:
  - notifier: mailgun
    state: CRITICAL
    to: ["ops@example.com"]
