appscodeicinga:
##
## Ihinga secret configaration
## https://github.com/appscode/searchlight/blob/master/docs/user-guide/icinga2/deployment.md#create-deployment
##

#  env:
#  caCrt:
#  ichingaKey:
#  ichingaCrt:
#  notifyVia:
#  hipchatAuthToken:
#  hipchatTo:
#  mailgunDomain:
#  mailgunAPIKey:
#  mailgunPublicAPIKey:
#  mailgunFrom:
#  mailgunTo:
#  smtpHost:
#  smtpPort:
#  smtpInsecureSkipVerify:
#  smtpUsername:
#  smtpPassword:
#  smtpFrom:
#  smtpTo:
#  twilioAccountSid:
#  twilioAuthToken:
#  twilioFrom:
#  twilioTo:
#  slackAuthToken:
#  slackChannel:
#  plivoAuthId:
#  plivoAuthToken:
#  plivoFrom:
#  plivoTo:
  icinga:
    image: appscode/postgres
    imageTag: 9.5-v3-db
    apiPort: 5665
    tcpPort: 60006
  apiTargetPort: 5665
  webTargetPort: 80
  ido:
    image: appscode/postgres
    imageTag: 9.5-v3-db
    idoPort: 5432
  type: Opaque
appscodesearchlight:
  image: appscode/searchlight
  imagePullPolicy: Always
  imageTag: 1.5.3
