apiVersion: monitoring.appscode.com/v1alpha1
kind: ClusterAlert
metadata:
  name: env-demo-0
spec:
  check: env
  checkInterval: 30s
  alertInterval: 2m
  notifierSecretName: searchlight-notifier
  receivers:
  - notifier: mailgun
    state: CRITICAL
    to: ["ops@example.com"]
