apiVersion: v1
kind: Service
metadata:
  labels:
    app: searchlight
  name: searchlight-icinga
  namespace: default
spec:
  ports:
  - name: ui
    port: 80
    protocol: TCP
    targetPort: ui
  - name: icinga
    port: 5665
    protocol: TCP
    targetPort: icinga
  - name: web
    port: 56790
    protocol: TCP
    targetPort: ui
  selector:
    app: searchlight
  type: NodePort
