apiVersion: v1
kind: Service
metadata:
  labels:
    app: searchlight
  name: searchlight-icinga
  namespace: default
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: api
    port: 5665
    protocol: TCP
    targetPort: api
  - name: http
    port: 56790
    protocol: TCP
    targetPort: web
  selector:
    app: searchlight
  type: NodePort
