kind: Service
apiVersion: v1
metadata:
  name: searchlight-icinga
  namespace: kube-system
  labels:
    app: searchlight-icinga
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: api
      port: 5665
      targetPort: api
  selector:
    app: searchlight-icinga
