apiVersion: v1
kind: Service
metadata:
  name: appscode-alert
  namespace: kube-system
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: tcp
  - name: api
    port: 5665
    protocol: TCP
    targetPort: api
  selector:
    run: appscode-alert
