apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: searchlight
  name: acknowledgements.incidents.monitoring.appscode.com
spec:
  group: incidents.monitoring.appscode.com
  names:
    kind: Acknowledgement
    listKind: AcknowledgementList
    plural: acknowledgements
    singular: acknowledgement
  scope: Namespaced
  versions:
  - name: incidents
    schema:
      openAPIV3Schema:
        type: object
    served: true
    storage: false
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          request:
            properties:
              comment:
                description: Comment by user
                type: string
              skipNotify:
                description: Skip sending notification
                type: boolean
            required:
            - comment
            type: object
          response:
            properties:
              timestamp:
                description: The time at which the acknowledgement was done.
                format: date-time
                type: string
            type: object
        required:
        - request
        type: object
    served: true
    storage: false
