apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: searchlight
  name: podalerts.monitoring.appscode.com
spec:
  group: monitoring.appscode.com
  names:
    categories:
    - monitoring
    - appscode
    - all
    kind: PodAlert
    listKind: PodAlertList
    plural: podalerts
    singular: podalert
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.check
      name: CheckCommand
      type: string
    - jsonPath: .spec.paused
      name: Paused
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: 'Spec is the desired state of the PodAlert. More info: http://releases.k8s.io/release-1.2/docs/devel/api-conventions.md#spec-and-status'
            properties:
              alertInterval:
                description: How frequently notifications will be send
                type: string
              check:
                description: Icinga CheckCommand name
                type: string
              checkInterval:
                description: How frequently Icinga Service will be checked
                type: string
              notifierSecretName:
                description: Secret containing notifier credentials
                type: string
              paused:
                description: Indicates that Check is paused Icinga Services are removed
                type: boolean
              podName:
                type: string
              receivers:
                description: NotifierParams contains information to send notifications
                  for Incident State, UserUid, Method
                items:
                  properties:
                    notifier:
                      description: How this notification will be sent
                      type: string
                    state:
                      description: For which state notification will be sent
                      type: string
                    to:
                      description: To whom notification will be sent
                      items:
                        type: string
                      type: array
                  type: object
                type: array
              selector:
                description: A label selector is a label query over a set of resources.
                  The result of matchLabels and matchExpressions are ANDed. An empty
                  label selector matches all objects. A null label selector matches
                  no objects.
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      description: A label selector requirement is a selector that
                        contains values, a key, and an operator that relates the key
                        and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: operator represents a key's relationship to
                            a set of values. Valid operators are In, NotIn, Exists
                            and DoesNotExist.
                          type: string
                        values:
                          description: values is an array of string values. If the
                            operator is In or NotIn, the values array must be non-empty.
                            If the operator is Exists or DoesNotExist, the values
                            array must be empty. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: matchLabels is a map of {key,value} pairs. A single
                      {key,value} in the matchLabels map is equivalent to an element
                      of matchExpressions, whose key field is "key", the operator
                      is "In", and the values array contains only "value". The requirements
                      are ANDed.
                    type: object
                type: object
              vars:
                additionalProperties:
                  type: string
                description: Vars contains Icinga Service variables to be used in
                  CheckCommand
                type: object
            type: object
          status:
            properties:
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  for this BackupBatch. It corresponds to the BackupBatch's generation,
                  which is updated on mutation by the API Server.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
