apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    run: {{ template "fullname" . }}-appscode-searchlight
  name: {{ template "fullname" . }}-appscode-searchlight
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ template "fullname" . }}-appscode-searchlight
  template:
    metadata:
      labels:
        run: {{ template "fullname" . }}-appscode-searchlight
    spec:
      containers:
      - args:
        - --icinga-secret-name={{ template "fullname" . }}-appscode-icinga
        - --icinga-secret-namespace={{.Release.Namespace}}
        image: {{.Values.appscodesearchlight.image}}:{{.Values.appscodesearchlight.imageTag}}
        name: appscode-searchlight
