apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}-appscode-icinga'
  namespace: '{{.Values.appscodeicinga.namespace}}'
type: '{{.Values.appscodeicinga.type}}'
data:
  {{ if .Values.appscodeicinga..env }}
  .env: {{.Values.appscodeicinga..env}}
  {{ else }}
  .env: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
