apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    run: appscode-icinga-{{ template "fullname" . }}
  name: appscode-icinga-{{ template "fullname" . }}
spec:
  ports:
  - name: web
    port: {{.Values.appscodeicinga.webTargetPort}}
    targetPort: web
  - name: api
    port: {{.Values.appscodeicinga.apiTargetPort}}
    targetPort: api
  selector:
    run: "appscode-icinga-{{ template "fullname" . }}"

