apiVersion: monitoring.appscode.com/v1alpha1
kind: ClusterAlert
metadata:
  name: any-http
  namespace: demo
spec:
  check: any-http
  vars:
    count: '1'
  checkInterval: 30s
  alertInterval: 2m
  notifierSecretName: notifier-config
  receivers:
  - notifier: Mailgun
    state: Critical
    to: ["ops@example.com"]
